(deftheme thanhpk-emacs
  "Created 2016-09-19.")

(custom-theme-set-variables
 'thanhpk-emacs
 '(c-basic-offset 2)
 '(fill-nobreak-invisible t)
 '(indent-tabs-mode t)
 '(js-indent-level 2)
 '(standard-indent 2)
 '(tab-width 2)
 '(custom-safe-themes (quote ("20d76b0b4f556aa943db5b59dc423e54556feb3edd6af4e903bb06c7c831fba7" "1157a4055504672be1df1232bed784ba575c60ab44d8e6c7b3800ae76b42f8bd" "cf08ae4c26cacce2eebff39d129ea0a21c9d7bf70ea9b945588c1c66392578d1" "5ee12d8250b0952deefc88814cf0672327d7ee70b16344372db9460e9a0e3ffc" "52588047a0fe3727e3cd8a90e76d7f078c9bd62c0b246324e557dfa5112e0d0c" "7f1263c969f04a8e58f9441f4ba4d7fb1302243355cb9faecb55aec878a06ee9" default)))
 '(font-use-system-font t)
 '(tool-bar-mode nil))

(custom-theme-set-faces
 'thanhpk-emacs
 '(default ((((class color) (min-colors 89)) (:background "#EDEDED" :foreground "#2E3436"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#00BBFF"))))
 '(border-color ((((class color) (min-colors 89)) (:background "#EDEDED"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#E6E6E6"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width -1 :style released-button) :background "white" :foreground "#2E3436"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#C6C6C6" :background "white"))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#CCCCCC" :background "black"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#0084C8" :bold t))))
 '(region ((((class color) (min-colors 89)) (:foreground unspecified :background "#C2D5E9"))))
 '(dired-header ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(widget-button ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(success ((((class color) (min-colors 89)) (:bold t :foreground "#4E9A06"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#CE5C00"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#B50000"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#A020F0"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#F5666D"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#204A87"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#00578E" :bold t))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold t :foreground "#A52A2A"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#4E9A06"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#2F8B58" :bold t))))
 '(font-lock-variable-name-face ((t (:foreground "#0084C8" :weight bold))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#F5666D" :bold t))))
 '(link ((((class color) (min-colors 89)) (:underline t :foreground "#0066CC"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#6799CC"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "white" :background "#4A90D9"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "white" :background "#77A4DD"))))
 '(erc-action-face ((((class color) (min-colors 89)) (:foreground "#F5666D"))))
 '(erc-button ((((class color) (min-colors 89)) (:foreground "#A8799C"))))
 '(erc-current-nick-face ((((class color) (min-colors 89)) (:bold t :foreground "#FF7092"))))
 '(erc-error-face ((((class color) (min-colors 89)) (:foreground "#F5666D" :bold t))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "black"))))
 '(erc-keyword-face ((((class color) (min-colors 89)) (:foreground "#F5666D"))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:bold t :foreground "#FF8CA7"))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#0084C8"))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "black"))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#4CB64A"))))
 '(magit-log-sha1 ((((class color) (min-colors 89)) (:foreground "#FF7092"))))
 '(magit-log-head-label-local ((((class color) (min-colors 89)) (:foreground "#4F78B5"))))
 '(magit-log-head-label-remote ((((class color) (min-colors 89)) (:foreground "#4CB64A"))))
 '(magit-branch ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(magit-section-title ((((class color) (min-colors 89)) (:bold t :foreground "#00578E"))))
 '(magit-item-highlight ((((class color) (min-colors 89)) (:background "#FEFFBF"))))
 '(magit-diff-add ((((class color) (min-colors 89)) (:bold t :foreground "#4CB64A"))))
 '(magit-diff-del ((((class color) (min-colors 89)) (:bold nil :foreground "#F5666D"))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:foreground "#00578E"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:bold t :foreground "#4F78B5"))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:foreground "#00578E"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:bold t :foreground "#9CBB43"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:foreground "#00578E"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:bold t :foreground "#9CBB43"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:bold t :foreground "#0084C8"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:bold t :foreground "#FF7092"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#FF7092"))))
 '(gnus-button ((((class color) (min-colors 89)) (:bold t :foreground "#00578E"))))
 '(gnus-cite-1 ((((class color) (min-colors 89)) (:foreground "#00578E"))))
 '(gnus-cite-2 ((((class color) (min-colors 89)) (:foreground "#0084C8"))))
 '(diff-added ((((class color) (min-colors 89)) (:bold t :foreground "#4E9A06"))))
 '(diff-removed ((((class color) (min-colors 89)) (:bold t :foreground "#F5666D")))))

(provide-theme 'thanhpk-emacs)
